[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "novelpy"
authors = [{name = "Pelletier Pierre", email = "p.pelletier@unistra.fr"}, {name = "Wirtz Kevin", email = "kevin.wirtz@unistra.fr"}]
dynamic = ["version", "description"]
